# Generated by Django 2.1.2 on 2020-11-18 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=128)),
                ('coupon_content', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=128)),
                ('coupon_name', models.CharField(max_length=128)),
                ('coupon_content', models.TextField(default='')),
                ('term', models.IntegerField(default=180)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.shop'),
        ),
    ]
