# Generated by Django 2.1.2 on 2020-11-25 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20201125_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
