# Generated by Django 2.1.2 on 2020-11-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20201125_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='term',
            field=models.IntegerField(null=True),
        ),
    ]
