# Generated by Django 2.1.2 on 2020-11-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_auto_20201125_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
