# Generated by Django 2.1.2 on 2020-11-25 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20201125_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Shop'),
        ),
    ]
