# Generated by Django 2.1.2 on 2020-11-25 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_auto_20201125_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='limit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Shop'),
        ),
    ]
